# fse_type: FSEType,
# attack_type: AttackType,
# data_path: String,
# attributes: Option<Vec<String>>,
# fse_params: Option<Vec<f64>>,
# p_norm: Option<u8>,
[[test_suites]]
"fse_type" = "lpfse_ihbe"
"attack_type" = "mle_attack"
"data_path" = "../data/test.csv"
"fse_params" = [ 1e-2 ]
"attributes" = ["order_number"]
"size" = 100000
"shuffle" = true

[[test_suites]]
"fse_type" = "pfse"
"attack_type" = "mle_attack"
"data_path" = "../data/test.csv"
"attributes" = ["order_number"]
"fse_params" = [0.25, 1.0, 0.05]
"size" = 100000
"shuffle" = true

[[test_suites]]
"fse_type" = "dte"
"attack_type" = "mle_attack"
"data_path" = "../data/test.csv"
"attributes" = ["order_number"]
"size" = 100000
"shuffle" = true

[[test_suites]]
"fse_type" = "rnd"
"attack_type" = "mle_attack"
"data_path" = "../data/test.csv"
"attributes" = ["order_number"]
"size" = 100000
"shuffle" = true
