# fse_type: FSEType,
# attack_type: AttackType,
# data_path: String,
# attributes: Option<Vec<String>>,
# fse_params: Option<Vec<f64>>,
# p_norm: Option<u8>,

"fse_type" = "lpfse_bhe"
"attack_type" = "lp_optimization"
"data_path" = "../data/test.csv"
"attributes" = [ "order_number" ]
"fse_params" = [ 2e-10 ]
"size" = 1000
"p_norm" = 4
"shuffle" = true
