# fse_type: FSEType,
# attack_type: AttackType,
# data_path: String,
# attributes: Option<Vec<String>>,
# fse_params: Option<Vec<f64>>,
# p_norm: Option<u8>,

"fse_type" = "dte"
"attack_type" = "lp_optimization"
"data_path" = "../data/test.csv"
"attributes" = [ "order_number" ]
"fse_params" = [ 2e-10, 0.25, 1.0 ]
"size" = 10000
"p_norm" = 4
