# fse_type: FSEType,
# attack_type: AttackType,
# data_path: String,
# attributes: Option<Vec<String>>,
# fse_params: Option<Vec<f64>>,
# p_norm: Option<u8>,

"fse_type" = "pfse"
"attack_type" = "mle_attack"
"data_path" = "../data/test.csv"
"attributes" = [ "order_number" ]
"fse_params" = [ 0.25, 1.0, 0.0009765625 ]
"size" = 10000
"p_norm" = 4
"shuffle" = true
